# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09

Description: Create-Infra-Ex

Parameters:
  EnvironmentName:
    Description: name
    Type: String


Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - webserver
      KeyName: udacity
      ImageId: 'ami-09d56f8956ab235b3' 
      InstanceType: t3.micro

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
